import Foundation

/// Every key the interface uses (`LC-14`).
///
/// Only the **keys** live in Swift; the translations stay in `Resources/<code>.lproj/Localizable.strings`, so
/// adding a language is still adding one directory and no code (`LC-2`). What the enum buys is that a
/// mistyped key does not compile, and that the tests can enumerate exactly what the interface asks for.
///
/// A key is an identifier, like `KeyCatalog.Entry.name` (`LC-12`). Removed keys are not reused (`LC-16`).
enum StringKey: String, CaseIterable {

    // MARK: - Menu bar popover

    case menuSubtitle = "menu.subtitle"
    case menuModeLabel = "menu.mode.label"
    case menuModeSimple = "menu.mode.simple"
    case menuModeScenario = "menu.mode.scenario"
    case menuLaunchAtLogin = "menu.launch_at_login"
    case menuQuit = "menu.quit"
    case menuGrantAccessibility = "menu.grant_accessibility"
    case menuGrantScreenRecording = "menu.grant_screen_recording"
    case menuLanguage = "menu.language"
    case menuLanguageFollowSystem = "menu.language.follow_system"

    // MARK: - Running

    case runStart = "run.start"
    case runStop = "run.stop"
    case runReady = "run.ready"
    case runStopped = "run.stopped"
    case runCountdown = "run.countdown"
    case runProgressStep = "run.progress.step"
    case runProgressIterationOfTotal = "run.progress.iteration_of_total"
    case runProgressIteration = "run.progress.iteration"
    case runCompletedSteps = "run.completed.steps"
    case runCompletedIterations = "run.completed.iterations"
    case runFailed = "run.failed"

    // MARK: - Recording

    case recordButton = "record.button"
    case recordHint = "record.hint"
    case recordInProgress = "record.in_progress"
    case recordFinished = "record.finished"
    case recordNothingCaptured = "record.nothing_captured"
    case recordTapFailed = "record.tap_failed"
    case recordDefaultName = "record.default_name"
    case recordWarningMultipleApplications = "record.warning.multiple_applications"
    case recordWarningAbsoluteSteps = "record.warning.absolute_steps"

    // MARK: - Floating panel

    case panelRecordingTitle = "panel.recording_title"
    case panelFinishHint = "panel.finish_hint"
    case panelStopHint = "panel.stop_hint"
    case panelFinish = "panel.finish"
    case panelStop = "panel.stop"
    case panelGestures = "panel.gestures"

    // MARK: - Simple mode

    case simpleInterval = "simple.interval"
    case simpleRepeat = "simple.repeat"
    case simpleRepeatUnit = "simple.repeat.unit"
    case simpleScenarioName = "simple.scenario_name"
    case simplePositionLabel = "simple.position.label"
    case simplePositionCursor = "simple.position.cursor"
    case simplePositionFixed = "simple.position.fixed"
    case simplePointNone = "simple.point.none"
    case simplePointCoordinates = "simple.point.coordinates"
    case simplePointChoose = "simple.point.choose"
    case simplePointChooseAgain = "simple.point.choose_again"
    case simpleCursorHint = "simple.cursor_hint"
    case simplePickingPoint = "simple.picking_point"
    case simplePointCancelled = "simple.point_cancelled"
    case simplePointSaved = "simple.point_saved"
    case simpleLockToggle = "simple.lock.toggle"
    case simpleLockApplication = "simple.lock.application"
    case simpleLockChoose = "simple.lock.choose"
    case simpleLockClosed = "simple.lock.closed"
    case simpleLockRefresh = "simple.lock.refresh"
    case simpleLockHint = "simple.lock.hint"
    case simpleApplicationFallbackName = "simple.application.fallback_name"

    // MARK: - Scenario section of the popover

    case scenarioPickerLabel = "scenario.picker.label"
    case scenarioPickerEmpty = "scenario.picker.empty"
    case scenarioNoneAtAll = "scenario.none_at_all"
    case scenarioReadOnlyBlocker = "scenario.read_only_blocker"
    case scenarioNeedsScreenRecording = "scenario.needs_screen_recording"
    case scenarioOpenEditor = "scenario.open_editor"
    case scenarioOpenEditorEllipsis = "scenario.open_editor_ellipsis"
    case scenarioSummarySteps = "scenario.summary.steps"
    case scenarioSummaryLoops = "scenario.summary.loops"
    case scenarioSummaryWithLoops = "scenario.summary.with_loops"
    case scenarioSummaryUntilStopped = "scenario.summary.until_stopped"

    // MARK: - Editor window

    case editorTitle = "editor.title"
    case editorRunningNotice = "editor.running_notice"
    case editorSelectAStep = "editor.select_a_step"
    case editorNewScenario = "editor.new_scenario"
    case editorDuplicateScenario = "editor.duplicate_scenario"
    case editorDeleteScenario = "editor.delete_scenario"
    case editorLoadIssues = "editor.load_issues"
    case editorUnnamed = "editor.unnamed"
    case editorReadOnlyBadge = "editor.read_only_badge"
    case editorEmptyTitle = "editor.empty.title"
    case editorEmptyAction = "editor.empty.action"
    case editorNewerFormatTitle = "editor.newer_format.title"
    case editorNewerFormatDetail = "editor.newer_format.detail"
    case editorScenarioName = "editor.scenario_name"
    case editorRepeatUntilStopped = "editor.repeat_until_stopped"
    case editorIterationCount = "editor.iteration_count"
    case editorLockToggle = "editor.lock.toggle"
    case editorLockApplication = "editor.lock.application"
    case editorLockChoose = "editor.lock.choose"
    case editorLockRefresh = "editor.lock.refresh"
    case editorNotChosen = "editor.not_chosen"
    case editorAddStep = "editor.add_step"
    case editorDuplicateStep = "editor.duplicate_step"
    case editorDeleteStep = "editor.delete_step"
    case editorDragToReorder = "editor.drag_to_reorder"
    case editorAnchorNeedsLock = "editor.anchor_needs_lock"
    case editorLockedNotRunning = "editor.locked_not_running"
    case editorNoWindowForLocked = "editor.no_window_for_locked"

    // MARK: - Step summaries in the list

    case summaryHold = "summary.hold"
    case summaryScroll = "summary.scroll"
    case summaryMove = "summary.move"
    case summaryDrag = "summary.drag"
    case summaryTypeEmpty = "summary.type_empty"
    case summaryType = "summary.type"
    case summaryKey = "summary.key"
    case summaryTargetCursor = "summary.target.cursor"
    case summaryTargetPoint = "summary.target.point"
    case summaryTargetCorner = "summary.target.corner"
    case summaryTargetTemplate = "summary.target.template"
    case summaryTargetTemplateMissing = "summary.target.template_missing"
    case summaryTargetTextEmpty = "summary.target.text_empty"
    case summaryTargetText = "summary.target.text"

    // MARK: - Step detail

    case stepActionSection = "step.action.section"
    case stepActionKind = "step.action.kind"
    case stepPosition = "step.position"
    case stepReleasePoint = "step.release_point"
    case stepRepeatSection = "step.repeat.section"
    case stepRepeatCount = "step.repeat.count"
    case stepRepeatUnit = "step.repeat.unit"
    case stepDelayAfter = "step.delay_after"
    case stepMinimumGapHint = "step.minimum_gap_hint"
    case stepButton = "step.button"
    case stepClickCount = "step.click_count"
    case stepHold = "step.hold"
    case stepDoubleClickHint = "step.double_click_hint"
    case stepHoldHint = "step.hold_hint"
    case stepScrollUnit = "step.scroll.unit"
    case stepScrollHorizontal = "step.scroll.horizontal"
    case stepScrollVertical = "step.scroll.vertical"
    case stepScrollHint = "step.scroll.hint"
    case stepMoveHint = "step.move_hint"
    case stepDragHint = "step.drag_hint"
    case stepTypeContent = "step.type.content"
    case stepTypePerKeyHint = "step.type.per_key_hint"
    case stepTypeChunkedHint = "step.type.chunked_hint"
    case stepKey = "step.key"
    case stepModifiers = "step.modifiers"
    case stepKeyPreview = "step.key_preview"
    case stepKeyActivationHint = "step.key_activation_hint"
    case stepKeyNoLockHint = "step.key_no_lock_hint"
    case stepTargetKind = "step.target.kind"
    case stepTargetCursorHint = "step.target.cursor_hint"
    case stepTargetCoordinates = "step.target.coordinates"
    case stepTargetChoosePoint = "step.target.choose_point"
    case stepTargetCornerOffset = "step.target.corner_offset"
    case stepTargetAnchorHint = "step.target.anchor_hint"
    case stepTargetAnchorNeedsLock = "step.target.anchor_needs_lock"
    case stepTargetTemplate = "step.target.template"
    case stepTargetCaptureRegion = "step.target.capture_region"
    case stepTargetCaptureAgain = "step.target.capture_again"
    case stepTargetTemplateHint = "step.target.template_hint"
    case stepTargetText = "step.target.text"
    case stepTargetTextHint = "step.target.text_hint"
    case stepTemplateNotCaptured = "step.template.not_captured"
    case stepTemplateFileMissing = "step.template.file_missing"
    case stepThreshold = "step.threshold"
    case stepWaitAtMost = "step.wait_at_most"
    case stepOnTimeout = "step.on_timeout"
    case stepOnTimeoutStop = "step.on_timeout.stop"
    case stepOnTimeoutSkip = "step.on_timeout.skip"
    case stepSearchRegion = "step.search_region"
    case stepSearchRegionClear = "step.search_region.clear"
    case stepSearchRegionPick = "step.search_region.pick"
    case stepWaitHint = "step.wait_hint"
    case stepRegionWholeScreen = "step.region.whole_screen"
    case stepRegionAbsolute = "step.region.absolute"
    case stepRegionWindowRelative = "step.region.window_relative"

    // MARK: - Actions and targets

    case actionClick = "action.click"
    case actionScroll = "action.scroll"
    case actionMove = "action.move"
    case actionDrag = "action.drag"
    case actionType = "action.type"
    case actionPressKey = "action.press_key"
    case targetCursor = "target.cursor"
    case targetFixedPoint = "target.fixed_point"
    case targetWindowRelative = "target.window_relative"
    case targetTemplate = "target.template"
    case targetText = "target.text"
    case buttonLeft = "button.left"
    case buttonRight = "button.right"
    case buttonMiddle = "button.middle"
    case cornerTopLeft = "corner.top_left"
    case cornerTopRight = "corner.top_right"
    case cornerBottomLeft = "corner.bottom_left"
    case cornerBottomRight = "corner.bottom_right"
    case keyNumpadEnter = "key.numpad_enter"

    // MARK: - Overlays

    case overlayPickPoint = "overlay.pick_point"
    case overlaySearchRegion = "overlay.search_region"
    case overlayTemplateRegion = "overlay.template_region"

    // MARK: - Errors

    case errorIntervalNotAnInteger = "error.interval.not_an_integer"
    case errorIntervalOutOfRange = "error.interval.out_of_range"
    case errorRepeatNotAnInteger = "error.repeat.not_an_integer"
    case errorRepeatOutOfRange = "error.repeat.out_of_range"
    case errorLockMissingSelection = "error.lock.missing_selection"
    case errorLockNotRunning = "error.lock.not_running"
    case errorFixedPointMissing = "error.fixed_point_missing"
    case errorEmptyScenario = "error.empty_scenario"
    case errorAccessibilityDenied = "error.accessibility_denied"
    case errorMissingLockedApplication = "error.missing_locked_application"
    case errorLockedApplicationNotRunning = "error.locked_application_not_running"
    case errorLockedApplicationTerminated = "error.locked_application_terminated"
    case errorPointOutsideLockedApplication = "error.point_outside_locked_application"
    case errorAnchorWindowUnavailable = "error.anchor_window_unavailable"
    case errorActivationFailed = "error.activation_failed"
    case errorUnknownKey = "error.unknown_key"
    case errorTargetNotFound = "error.target_not_found"
    case errorLaunchAtLogin = "error.launch_at_login"
    case errorSchemaTooNew = "error.schema_too_new"
    case errorUnknownAction = "error.unknown_action"
    case errorUnknownTarget = "error.unknown_target"
    case errorScreenRecordingDenied = "error.screen_recording_denied"
    case errorNoDisplay = "error.no_display"
    case errorPixelScaleUnreadable = "error.pixel_scale_unreadable"
    case errorScreenCaptureFailed = "error.screen_capture_failed"
    case issueSchemaReadOnly = "issue.schema_read_only"
    case issueUnreadable = "issue.unreadable"

    // MARK: - Names written into scenario.json

    /// `LC-11`: translated once, when the Scenario is created, and never again.
    case dataDuplicateSuffix = "data.duplicate_suffix"
    case dataNewScenarioName = "data.new_scenario_name"
}
